export const ADD_DATA="AddData"
export const ADD_DATA_ERROR="AddDataError"
export const REMOVE_DATA="RemoveData"
export const REMOVE_DATA_ERROR="RemoveDataError"
export const ADD_CART_DATA="AddCartData"
export const ADD_CART_DATA_ERROR="AddCartDataError"